# Stage 1: Build the application
FROM gradle:8.13.0-jdk17-alpine AS build
WORKDIR /app

# Copy the Gradle wrapper and build files
COPY gradlew .
COPY gradle ./gradle

# Copy the build configuration and source code
COPY . ./

# Build the application
RUN ./gradlew kafka-reddits-processor:shadowJar

# Stage 2: Create the runtime image
FROM openjdk:17-jdk-slim
WORKDIR /app

RUN mkdir /app/output

# Copy the JAR file from the build stage
COPY --from=build /app/kafka-reddits-processor/build/libs/*.jar processor-reddit.jar

ENV INPUT_TOPIC="subreddits"
ENV OUTPUT_TOPIC="results"
ENV BOOTSTRAP_SERVERS="broker-1:19092, broker-2:19092, broker-3:19092"
ENV GROUP_ID="subreddits-group-1"

# Run the application
ENTRYPOINT ["java", "-jar", "processor-reddit.jar"]